[package]
name = "dioxionary"
version = "1.0.2"
edition = "2021"
authors = ["vaaandark <vaaandark@gmail.com>"]
description = "Remember all words in terminal!"
license = "GPL-2.0"
homepage = "https://github.com/vaaandark/dioxionary"
repository = "https://github.com/vaaandark/dioxionary"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dioxionary"
path = "src/main.rs"

[lib]
name = "dioxionary"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
reqwest = { version = "0.11.20", features = ["blocking", "default-tls"], default-features = false }
hyper = "0.14.27"
scraper = { default-features = false, version = "0.13.0" }
dirs = "4.0.0"
rusqlite = "0.28.0"
chrono = { features = ["clock"], default-features = false, version = "0.4" }
itertools = { default-features = false, version = "0.10.5" }
clap = { version = "4.4.2", features = ["derive", "help"], default-features = false }
prettytable = { default-features = false, version = "0.10.0" }
eio = { default-features = false, version = "0.1.2" }
flate2 = { version = "1.0.27", features = ["any_zlib", "libz-sys"], default-features = false }
rustyline = { default-features = false, version = "10.1.1" }
dialoguer = { default-features = false, version = "0.10.4" }
tokio = { version = "1.32.0", default-features = false }
rodio = { default-features = false, version = "0.17.1" }
clap_complete = "4.4.0"
anyhow = "1.0.75"
