[package]
name = "dioxionary"
version = "1.0.0"
edition = "2021"
authors = ["vaaandark <vaaandark@gmail.com>"]
description = "Remember all words in terminal!"
license = "GPL-2.0"
homepage = "https://github.com/vaaandark/dioxionary"
repository = "https://github.com/vaaandark/dioxionary"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dioxionary"
path = "src/main.rs"

[lib]
name = "dioxionary"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking"] }
hyper = "0.14.20"
scraper = "0.13.0"
dirs = "4.0.0"
rusqlite = "0.28.0"
chrono = "0.4"
itertools = "0.10.5"
clap = { version = "4.1.1", features = ["derive"] }
prettytable = "0.10.0"
thiserror = "1.0.38"
eio = "0.1.2"
flate2 = { version = "1.0.25", features = ["zlib"] }
rustyline = "10.1.1"
dialoguer = "0.10.4"
tokio = { version = "1.28.2", features = ["rt"] }
rodio = "0.16.0"
clap_complete = "4.3.0"
