on: [push]

name: CI build

jobs:
  build:
    name: Build for ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dioxionary
            asset_name: dioxionary-linux-amd64
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get update && sudo apt-get install -y libssl-dev libsqlite3-dev libasound2-dev
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
          strip: true
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.asset_name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.artifact_name }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.platform.target }}/release/${{ matrix.platform.artifact_name }}
          asset_name: ${{ matrix.platform.asset_name }}
          tag: ${{ github.ref }}
